// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: sstable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_INSERT      Operation = 1
	Operation_OPERATION_DELETE      Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_INSERT",
		2: "OPERATION_DELETE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_INSERT":      1,
		"OPERATION_DELETE":      2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_sstable_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_sstable_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0}
}

type ManifestEntry_Op int32

const (
	ManifestEntry_OP_UNSPECIFIED ManifestEntry_Op = 0
	ManifestEntry_OP_ADDTABLE    ManifestEntry_Op = 1
	ManifestEntry_OP_REMOVETABLE ManifestEntry_Op = 2
	ManifestEntry_OP_CLEARTABLE  ManifestEntry_Op = 3
)

// Enum value maps for ManifestEntry_Op.
var (
	ManifestEntry_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_ADDTABLE",
		2: "OP_REMOVETABLE",
		3: "OP_CLEARTABLE",
	}
	ManifestEntry_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_ADDTABLE":    1,
		"OP_REMOVETABLE": 2,
		"OP_CLEARTABLE":  3,
	}
)

func (x ManifestEntry_Op) Enum() *ManifestEntry_Op {
	p := new(ManifestEntry_Op)
	*p = x
	return p
}

func (x ManifestEntry_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManifestEntry_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_sstable_proto_enumTypes[1].Descriptor()
}

func (ManifestEntry_Op) Type() protoreflect.EnumType {
	return &file_sstable_proto_enumTypes[1]
}

func (x ManifestEntry_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManifestEntry_Op.Descriptor instead.
func (ManifestEntry_Op) EnumDescriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{1, 0}
}

type SSTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries   []*SSTable_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Name      *string          `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Filter    *SSTable_Filter  `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	First     []byte           `protobuf:"bytes,4,opt,name=first,proto3,oneof" json:"first,omitempty"`
	Last      []byte           `protobuf:"bytes,5,opt,name=last,proto3,oneof" json:"last,omitempty"`
	CreatedOn []byte           `protobuf:"bytes,6,opt,name=created_on,json=createdOn,proto3,oneof" json:"created_on,omitempty"`
	Size      *int64           `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"`
}

func (x *SSTable) Reset() {
	*x = SSTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTable) ProtoMessage() {}

func (x *SSTable) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTable.ProtoReflect.Descriptor instead.
func (*SSTable) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0}
}

func (x *SSTable) GetEntries() []*SSTable_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SSTable) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SSTable) GetFilter() *SSTable_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SSTable) GetFirst() []byte {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *SSTable) GetLast() []byte {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *SSTable) GetCreatedOn() []byte {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *SSTable) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type ManifestEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    ManifestEntry_Op `protobuf:"varint,1,opt,name=op,proto3,enum=gostore.proto.ManifestEntry_Op" json:"op,omitempty"`
	Level int32            `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Table *SSTable         `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *ManifestEntry) Reset() {
	*x = ManifestEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestEntry) ProtoMessage() {}

func (x *ManifestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestEntry.ProtoReflect.Descriptor instead.
func (*ManifestEntry) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestEntry) GetOp() ManifestEntry_Op {
	if x != nil {
		return x.Op
	}
	return ManifestEntry_OP_UNSPECIFIED
}

func (x *ManifestEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ManifestEntry) GetTable() *SSTable {
	if x != nil {
		return x.Table
	}
	return nil
}

type SSTable_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op    Operation `protobuf:"varint,3,opt,name=op,proto3,enum=gostore.proto.Operation" json:"op,omitempty"`
}

func (x *SSTable_Entry) Reset() {
	*x = SSTable_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTable_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTable_Entry) ProtoMessage() {}

func (x *SSTable_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTable_Entry.ProtoReflect.Descriptor instead.
func (*SSTable_Entry) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SSTable_Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SSTable_Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SSTable_Entry) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_OPERATION_UNSPECIFIED
}

type SSTable_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SSTable_Filter) Reset() {
	*x = SSTable_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTable_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTable_Filter) ProtoMessage() {}

func (x *SSTable_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTable_Filter.ProtoReflect.Descriptor instead.
func (*SSTable_Filter) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SSTable_Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SSTable_Filter) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_sstable_proto protoreflect.FileDescriptor

var file_sstable_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x67, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3,
	0x03, 0x0a, 0x07, 0x53, 0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x53, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x53, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x01, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x03, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x48, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x1a, 0x59, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x02, 0x6f, 0x70, 0x1a, 0x30, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x67, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2c, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x6f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x53, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x50, 0x0a, 0x02, 0x4f,
	0x70, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x54,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x5f, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50,
	0x5f, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x2a, 0x52, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x50,
	0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10,
	0x02, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x6e, 0x6b, 0x6d, 0x63, 0x71, 0x75, 0x61, 0x64, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sstable_proto_rawDescOnce sync.Once
	file_sstable_proto_rawDescData = file_sstable_proto_rawDesc
)

func file_sstable_proto_rawDescGZIP() []byte {
	file_sstable_proto_rawDescOnce.Do(func() {
		file_sstable_proto_rawDescData = protoimpl.X.CompressGZIP(file_sstable_proto_rawDescData)
	})
	return file_sstable_proto_rawDescData
}

var file_sstable_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sstable_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sstable_proto_goTypes = []interface{}{
	(Operation)(0),         // 0: gostore.proto.Operation
	(ManifestEntry_Op)(0),  // 1: gostore.proto.ManifestEntry.Op
	(*SSTable)(nil),        // 2: gostore.proto.SSTable
	(*ManifestEntry)(nil),  // 3: gostore.proto.ManifestEntry
	(*SSTable_Entry)(nil),  // 4: gostore.proto.SSTable.Entry
	(*SSTable_Filter)(nil), // 5: gostore.proto.SSTable.Filter
}
var file_sstable_proto_depIdxs = []int32{
	4, // 0: gostore.proto.SSTable.entries:type_name -> gostore.proto.SSTable.Entry
	5, // 1: gostore.proto.SSTable.filter:type_name -> gostore.proto.SSTable.Filter
	1, // 2: gostore.proto.ManifestEntry.op:type_name -> gostore.proto.ManifestEntry.Op
	2, // 3: gostore.proto.ManifestEntry.table:type_name -> gostore.proto.SSTable
	0, // 4: gostore.proto.SSTable.Entry.op:type_name -> gostore.proto.Operation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sstable_proto_init() }
func file_sstable_proto_init() {
	if File_sstable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sstable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTable_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTable_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sstable_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sstable_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sstable_proto_goTypes,
		DependencyIndexes: file_sstable_proto_depIdxs,
		EnumInfos:         file_sstable_proto_enumTypes,
		MessageInfos:      file_sstable_proto_msgTypes,
	}.Build()
	File_sstable_proto = out.File
	file_sstable_proto_rawDesc = nil
	file_sstable_proto_goTypes = nil
	file_sstable_proto_depIdxs = nil
}
