// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: sstable.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_INSERT Operation = 0
	Operation_DELETE Operation = 1
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "INSERT",
		1: "DELETE",
	}
	Operation_value = map[string]int32{
		"INSERT": 0,
		"DELETE": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_sstable_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_sstable_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0}
}

type SSTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*SSTable_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *SSTable) Reset() {
	*x = SSTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTable) ProtoMessage() {}

func (x *SSTable) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTable.ProtoReflect.Descriptor instead.
func (*SSTable) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0}
}

func (x *SSTable) GetEntries() []*SSTable_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SSTable_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op    Operation `protobuf:"varint,3,opt,name=op,proto3,enum=Operation" json:"op,omitempty"`
}

func (x *SSTable_Entry) Reset() {
	*x = SSTable_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSTable_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTable_Entry) ProtoMessage() {}

func (x *SSTable_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sstable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTable_Entry.ProtoReflect.Descriptor instead.
func (*SSTable_Entry) Descriptor() ([]byte, []int) {
	return file_sstable_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SSTable_Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SSTable_Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SSTable_Entry) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_INSERT
}

var File_sstable_proto protoreflect.FileDescriptor

var file_sstable_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x80, 0x01, 0x0a, 0x07, 0x53, 0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53,
	0x53, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02,
	0x6f, 0x70, 0x2a, 0x23, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x6c, 0x6c, 0x6f, 0x6e, 0x6b, 0x6d, 0x63, 0x71,
	0x75, 0x61, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sstable_proto_rawDescOnce sync.Once
	file_sstable_proto_rawDescData = file_sstable_proto_rawDesc
)

func file_sstable_proto_rawDescGZIP() []byte {
	file_sstable_proto_rawDescOnce.Do(func() {
		file_sstable_proto_rawDescData = protoimpl.X.CompressGZIP(file_sstable_proto_rawDescData)
	})
	return file_sstable_proto_rawDescData
}

var (
	file_sstable_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_sstable_proto_msgTypes  = make([]protoimpl.MessageInfo, 2)
	file_sstable_proto_goTypes   = []interface{}{
		(Operation)(0),        // 0: Operation
		(*SSTable)(nil),       // 1: SSTable
		(*SSTable_Entry)(nil), // 2: SSTable.Entry
	}
)
var file_sstable_proto_depIdxs = []int32{
	2, // 0: SSTable.entries:type_name -> SSTable.Entry
	0, // 1: SSTable.Entry.op:type_name -> Operation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sstable_proto_init() }
func file_sstable_proto_init() {
	if File_sstable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sstable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSTable_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sstable_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sstable_proto_goTypes,
		DependencyIndexes: file_sstable_proto_depIdxs,
		EnumInfos:         file_sstable_proto_enumTypes,
		MessageInfos:      file_sstable_proto_msgTypes,
	}.Build()
	File_sstable_proto = out.File
	file_sstable_proto_rawDesc = nil
	file_sstable_proto_goTypes = nil
	file_sstable_proto_depIdxs = nil
}
